# Generated by Django 4.2.4 on 2023-08-14 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('username', models.TextField(blank=True, null=True)),
                ('nid', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_hash', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('is_completed', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Document_shared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_docs', to='users.documents')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_docs', to='users.documents')),
                ('parties_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'documents_shared',
            },
        ),
        migrations.AddConstraint(
            model_name='documents',
            constraint=models.UniqueConstraint(fields=('document_id', 'user'), name='document_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='document_shared',
            constraint=models.UniqueConstraint(fields=('doc_id', 'owner_id'), name='document_unique'),
        ),
    ]
