# Generated by Django 4.2.4 on 2023-08-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='salt',
            field=models.TextField(blank=True),
        ),
    ]
