# Generated by Django 4.2.4 on 2023-08-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_onetimepassword_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
