# Generated by Django 4.2.4 on 2023-08-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AddField(
            model_name='documents',
            name='document_file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='users',
            name='firstname',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='lastname',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
